#version 430 core

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec4 position;
    vec4 velocity;
    vec2 properties;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

layout(std430, binding = 1) buffer GridCountBuffer {
    uint gridCounts[];
};

layout(std430, binding = 2) buffer GridIndicesBuffer {
    uint gridIndices[];
};

uniform int particleCount;
uniform int mode;

const float SMOOTHING_LENGTH = 0.18f;
const ivec3 GRID_RES = ivec3(28, 28, 28);
const vec3 BOX_MIN = vec3(-2.5f, 0.f, -2.5f);

int GetCellIndex(vec3 pos) {
    ivec3 cellCoords = ivec3(floor((pos - BOX_MIN) / SMOOTHING_LENGTH));
    cellCoords = clamp(cellCoords, ivec3(0), GRID_RES - ivec3(1));
    return cellCoords.x + cellCoords.y * GRID_RES.x + cellCoords.z * (GRID_RES.x * GRID_RES.y);
}

void main() {
    uint i = gl_GlobalInvocationID.x;

    if (mode == 0) {
        uint totalCells = GRID_RES.x * GRID_RES.y * GRID_RES.z;
        if (i >= totalCells) return;
        gridCounts[i] = 0;
    }

    if (mode == 1) {
        if (i >= particleCount) return;

        vec3 pos = particles[i].position.xyz;
        int cellIdx = GetCellIndex(pos);

        uint slot = atomicAdd(gridCounts[cellIdx], 1);

        if (slot < 64) {
            uint globalIndex = (cellIdx * 64) + slot;
            gridIndices[globalIndex] = i;
        }
    }
}